- name: 安装 daemon 相关依赖
  package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"

- name: 生成 chrony server 配置文件
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: 生效 chrony server 配置
  service:
    name: chronyd
    state: restarted

- block:
    - name: 主动同步时间
      shell: "ntpdate {{groups['kube-master'][0]}} | hwclock -w"
      when: "inventory_hostname != groups['kube-master'][0]"
  when: "DEPLOY_MODE == 'multiple-master'"

