- name: 插入 repository 记录
  lineinfile:
    path: "/etc/hosts"
    regexp: '{{ local_hostname }}'
    line: "{{local_hostname}}  {{dns_repository_hostname}}"

- name: 插入 registry 记录
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{dns_registry_hostname}}"
    line: "{{ hostvars[groups['worker'][0]]['ansible_ssh_host']  }} {{dns_registry_hostname}}"

- name: 插入 hosts 记录
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ item }}"
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
  with_items: "{{ groups['cluster_nodes'] }}"

- name: 添加主 DNS 解析
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{dns1}}"
    regexp: "nameserver {{dns1}}"
  when: 'dns1 is defined'

- name: 添加副 DNS 解析
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{dns2}}"
    regexp: "nameserver {{dns2}}"
  when: 'dns2 is defined'

