- block:
    - name: 在deploy 节点创建相关目录
      file: name=/opt/kube/kube-system/flannel state=directory

    - name: 配置 flannel DaemonSet yaml文件
      template: src=kube-flannel.yaml.j2 dest=/opt/kube/kube-system/flannel/kube-flannel.yaml
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- name: 创建flannel cni 相关目录
  file: name={{ item }} state=directory
  with_items:
    - /etc/cni/net.d
    - /opt/kube/images

- name: 下载flannel cni plugins
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
    - bridge
    - flannel
    - host-local
    - loopback
    - portmap

# 只需单节点执行一次
- name: 运行 flannel网络
  shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/flannel/ && sleep 5"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

# 删除原有cni配置
- name: 删除默认cni配置
  file: path=/etc/cni/net.d/10-default.conf state=absent

# 等待网络插件部署成功，视下载镜像速度而定
- name: 轮询等待flannel 运行，视下载镜像速度而定
  shell: "{{ bin_dir }}/kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' {{ inventory_hostname }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  delegate_to: "{{ groups['kube-master'][0] }}"
  retries: 15
  delay: 8
