- block:
    - name: 生成 traefik-ingress 部署文件
      template:
        src: ingress/traefik/traefik-ingress.yaml.j2
        dest: "{{ base_dir }}/manifests/ingress/traefik/traefik-ingress.yaml"

    - name: 创建 traefik 部署
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/ingress/traefik/traefik-ingress.yaml"
  when: 'ingress_backend == "traefik"'
  ignore_errors: true

- block:
    - name: 生成 nginx-ingress 部署文件
      template:
        src: ingress/nginx/nginx-ingress.yaml.j2
        dest: "{{ base_dir }}/manifests/ingress/nginx/nginx-ingress.yaml"

    - name: 创建 nginx 部署
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/ingress/nginx/nginx-ingress.yaml"
  when: 'ingress_backend == "nginx"'
  ignore_errors: true
