- name: 配置 Ip forward
  shell: "echo 'net.ipv4.ip_forward = 1' >> /usr/lib/sysctl.d/50-default.conf
  && sysctl -p /usr/lib/sysctl.d/50-default.conf "
  ignore_errors: true


- name: 获取docker版本信息
  shell: "{{ base_dir }}/bin/docker --version|cut -d' ' -f3"
  register: docker_ver
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: 转换docker版本信息为浮点数
  set_fact:
    DOCKER_VER: "{{ docker_ver.stdout.split('.')[0]|int + docker_ver.stdout.split('.')[1]|int/100 }}"
  tags: upgrade_docker, download_docker

- name: debug info
  debug: var="DOCKER_VER"
  tags: upgrade_docker, download_docker

- block:
    - name: 准备docker相关目录
      file: name={{ item }} state=directory
      with_items:
        - "{{ bin_dir }}"
        - /etc/docker

    - name: 下载 docker 二进制文件
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - docker-containerd
        - docker-containerd-shim
        - docker-init
        - docker-runc
        - docker
        - docker-containerd-ctr
        - dockerd
        - docker-proxy
      tags: upgrade_docker, download_docker
      when: "DOCKER_VER|float < 18.09"

    - name: 下载 docker 二进制文件(>= 18.09.x)
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - containerd
        - containerd-shim
        - docker-init
        - runc
        - docker
        - ctr
        - dockerd
        - docker-proxy
      tags: upgrade_docker, download_docker
      when: "DOCKER_VER|float >= 18.09"

    - name: docker命令自动补全
      copy: src=docker dest=/etc/bash_completion.d/docker mode=0644

    - name: docker国内镜像加速
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json

    - name: 创建docker的systemd unit文件
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker

    - name: 开机启用docker 服务
      shell: systemctl enable docker
      ignore_errors: true

    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    - name: 下载 docker-tag
      copy: src=docker-tag dest={{ bin_dir }}/docker-tag mode=0755

    - name: 轮询等待docker服务运行
      shell: "systemctl status docker.service|grep Active"
      register: docker_status
      until: '"running" in docker_status.stdout'
      retries: 8
      delay: 2
