bind:
  host: 0.0.0.0
  port: 8080
logging:
  level: info
db:
  host: mysql
  port: 3306
  user: root
  password: KubeOperator@admin123
  name: ko
jwt:
  secret: iXDgDaEYBzIzustW
  exp: 480
helm:
  repo:
    name: nexus
    url: http://nexus:8081/repository/helm
    username: admin
    password: admin123
kobe:
  host: kobe
  port: 8080
kotf:
  host: kotf
  port: 8080
grafana:
  host: grafana
  port: 3000
  username: admin
  password: admin