DEBUG: true
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: fit2openshift
DB_USER: root
DB_PASSWORD: 123456
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_PASSWORD:
SECRET_KEY: "33h+(k@zm7o#@j%7_1(8q8dlzn9%5ajml2_frgp5e2ikxzfw$8"