- block:
    - name: 插入 kubeapps-plus registry hosts 记录
      lineinfile:
        path: "/etc/hosts"
        regexp: "{{ kubeapps_registry_hostname }}"
        line: "{{ hostvars[groups['worker'][0]]['ansible_ssh_host'] }} {{ kubeapps_registry_hostname }}"

    - name: 插入 kubeapps-plus chartmuseum hosts 记录
      lineinfile:
        path: "/etc/hosts"
        regexp: "{{ kubeapps_chartmuseum_hostname }}"
        line: "{{ hostvars[groups['worker'][0]]['ansible_ssh_host'] }} {{ kubeapps_chartmuseum_hostname }}"

- block:
    - name: 尝试登陆 kubeapps-plus registry
      shell: "docker login {{ kubeapps_registry_hostname }} -u {{REGISTRY_ACCOUNT_NAME}} -p {{REGISTRY_ACCOUNT_PASSWORD}}"
      register: login_result
      until: login_result.rc == 0
      retries: 10
      delay: 10
      ignore_errors: true
