- import_tasks: scale-vsan.yml
  when:
    - 'storage_vsan_enabled is defined'
    - 'storage_vsan_enabled'

- import_tasks: scale-ceph.yml
  when:
    - 'storage_rook_ceph_enabled is defined'
    - 'storage_rook_ceph_enabled'

- import_tasks: kubeapps.yml
  when:
    - 'kubeapps_install is defined'
    - 'kubeapps_install'
