- name: prepare rook-ceph deploy directory
  file: name={{ base_dir }}/manifests/storage/rook state=directory

- name: prepare rook-cluster file
  template:
    src: rook/scale-ceph-cluster.yaml.j2
    dest: "{{ base_dir }}/manifests/storage/rook/cluster.yaml"

- name: deploy rook-cluster
  shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/storage/rook/cluster.yaml"
  ignore_errors: true

- name: prepare rook-blockpool file
  template:
    src: rook/scale-ceph-blockpool.yaml.j2
    dest: "{{ base_dir }}/manifests/storage/rook/blockpool.yaml"

- name: deploy rook-blockpool
  shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/storage/rook/blockpool.yaml"
  ignore_errors: true
