apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubeapps.chartsvc.fullname" . }}
  labels:
    app: {{ template "kubeapps.chartsvc.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.chartsvc.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubeapps.chartsvc.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubeapps.chartsvc.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- include "kubeapps.imagePullSecrets" . | indent 6 }}
      {{- if .Values.chartsvc.affinity }}
      affinity: {{- include "kubeapps.tplValue" (dict "value" .Values.chartsvc.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.chartsvc.nodeSelector }}
      nodeSelector: {{- include "kubeapps.tplValue" (dict "value" .Values.chartsvc.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.chartsvc.tolerations }}
      tolerations: {{- include "kubeapps.tplValue" (dict "value" .Values.chartsvc.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: chartsvc
          image: {{ template "kubeapps.image" (list .Values.chartsvc.image .Values.global) }}
          command:
            - /chartsvc
          args:
            - --mongo-user=root
            - --mongo-url={{ template "kubeapps.mongodb.fullname" . }}
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.existingSecret }}
                  key: mongodb-root-password
          ports:
            - name: http
              containerPort: {{ .Values.chartsvc.service.port }}
          {{- if .Values.chartsvc.livenessProbe }}
          livenessProbe: {{- toYaml .Values.chartsvc.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.chartsvc.readinessProbe }}
          readinessProbe: {{- toYaml .Values.chartsvc.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.chartsvc.resources }}
          resources: {{- toYaml .Values.chartsvc.resources | nindent 12 }}
          {{- end }}
