- hosts:
  - master
  tasks:
    - name: copy backup files
      unarchive:
        src: /etc/ansible/roles/cluster-backup/files/cluster-backup.zip
        dest: /

- hosts: etcd
  roles:
    - cluster-restore