- hosts: kube-master
  roles:
    - kube-master
    - kube-node
  tasks:
    - name: Making master nodes SchedulingDisabled
      shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }}"
      delegate_to: "{{ groups['kube-master'][0] }}"
      when: DEPLOY_MODE != "allinone"
      ignore_errors: true

    - name: Setting master role name
      shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
      ignore_errors: true

    - name: Download helm client
      copy: src={{ base_dir }}/bin/helm dest={{ bin_dir }}/helm mode=0755
