http_ingress:
  registry:
    name: f2c-registry-ui-ingress
    namespace: kube-system
  traefik:
    name: f2c-traefik-ingress
    namespace: kube-system
  grafana:
    name: f2c-grafana
    namespace: kube-operator
  prometheus:
    name: f2c-prometheus-server
    namespace: kube-operator
  weave:
    name: f2c-weave-ingress
    namespace: kube-operator
  kubeapps:
    name: kubeapps-registry-ingress
    namespace: kube-system

https_ingress:
  dashboard:
    name: f2c-dashboard-ingress
    namespace: kube-system

kube_version_main: "{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}"
