# 默认使用kube-proxy的 'iptables' 模式，可选 'ipvs' 模式(experimental)
PROXY_MODE: "iptables"

# 基础容器镜像

SANDBOX_IMAGE: "{{registry_prefix}}:{{registry_port}}/{{SANDBOX_IMAGE_NAME}}:{{SANDBOX_VERSION}}"

# Kubelet 根目录
KUBELET_ROOT_DIR: "/var/lib/kubelet"

# node节点最大pod 数
MAX_PODS: 100

# 配置为kube组件（kubelet,kube-proxy,dockerd等）预留的资源量
KUBE_RESERVED_ENABLED: "yes"
KUBE_RESERVED: "cpu=200m,memory=500Mi,ephemeral-storage=1Gi"

# 配置kubelet的hard eviction条件
HARD_EVICTION: "memory.available<200Mi,nodefs.available<10%"

# 配置 APISERVER 地址
KUBE_APISERVER: "{%- if inventory_hostname in groups['kube-master'] -%} \
                     https://{{ ansible_ssh_host }}:6443 \
                 {%- else -%} \
                     {%- if groups['kube-master']|length > 1 -%} \
                         https://127.0.0.1:6443 \
                     {%- else -%} \
                         https://{{ groups['kube-master'][0] }}:6443 \
                     {%- endif -%} \
                 {%- endif -%}"

# node 请求 apiserver 负载均衡算法，常见如下：
# "roundrobin": 基于服务器权重的轮询
# "leastconn": 基于服务器最小连接数
# "source": 基于请求源IP地址
# "uri": 基于请求的URI
BALANCE_ALG: "roundrobin"
CLUSTER_DNS_SVC_IP: "{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') }}"
CLUSTER_DNS_DOMAIN: "cluster.local"

# kubernetes 大版本号
kube_version_main: "{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}"