- name: stop firewalld
  service: "name=firewalld state=stopped enabled=no"

- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind utilities are installed.
  package: name=rpcbind state=present

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"


- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Create exports file.
  file:
    path: "/etc/exports"
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Add export
  blockinfile:
    path: "/etc/exports"
    marker: "#{mark} {{storage_nfs_server_path}}"
    block: "{{storage_nfs_server_path}} {{allow_ip}}(rw,sync,no_root_squash)"
    state: present
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length