- block:
    - name: create kube-system ceph admin secret
      shell: "{{ bin_dir }}/kubectl create secret generic ceph-admin-secret \
            --namespace=kube-system \
            --type=kubernetes.io/rbd \
            --from-literal=key={{ ceph_admin_secret }}"
      ignore_errors: true

    - name: create kube-system ceph user secret
      shell: "{{ bin_dir }}/kubectl create secret generic ceph-user-secret \
            --namespace=kube-system \
            --type=kubernetes.io/rbd \
            --from-literal=key={{ ceph_user_secret }}"
      ignore_errors: true

    - name: create default ceph secret
      shell: "{{ bin_dir }}/kubectl create secret generic ceph-user-secret \
            --namespace=default \
            --type=kubernetes.io/rbd \
            --from-literal=key={{ ceph_user_secret }}"
      ignore_errors: true

    - name: create kube-operator namespace
      shell: "kubectl create ns kube-operator"
      ignore_errors: true

    - name: create kube-operator ceph secret
      shell: "{{ bin_dir }}/kubectl create secret generic ceph-user-secret \
            --namespace=kube-operator \
            --type=kubernetes.io/rbd \
            --from-literal=key={{ ceph_user_secret }}"
      ignore_errors: true
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- block:
    - name: prepare external-ceph dir
      file: name={{ base_dir }}/manifests/storage/external-ceph state=directory

    - name: generate external-ceph storageclass file
      template:
        src: external-ceph/storageclass.yaml.j2
        dest: "{{ base_dir }}/manifests/storage/external-ceph/storageclass.yaml"

    - name: get storageclass
      command: "{{ bin_dir }}/kubectl get sc"
      register: sc_info

    - name: delete default storageclass
      shell: "{{ bin_dir }}/kubectl delete sc storageclass-default"
      when: '"storageclass-default" in sc_info.stdout'
      ignore_errors: true

    - name: begin deploying external-ceph storageclass
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/storage/external-ceph/storageclass.yaml"
      ignore_errors: true

    - name: set default storageClass
      shell: "{{ bin_dir }}/kubectl patch storageclass '{{ storageClassName }}' -p '{{ default_label }}'"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true
