- name: 创建F5-ctrl 部署文件
  template:
    src: f5-bigip.yml.j2
    dest: /tmp/f5-bigip.yml

- block:
    - name: 创建 secret
      shell: "kubectl create secret generic bigip-login --namespace kube-system --from-literal=username={{bigip_username}} --from-literal=password={{bigip_password}}"
      ignore_errors: true

    - name: 部署 f5-bigip-ctrl
      shell: "kubectl apply -f /tmp/f5-bigip.yml"

    - name: 轮询等待 f5-bigip-ctrl 启动
      shell: "{{ bin_dir }}/kubectl get pod -n kube-system | grep 'bigip' | awk '{print $3}'"
      register: f5_status
      until: f5_status.stdout == 'Running'
      retries: 20
      delay: 5

    - name: attach a virtual server to kubernetes http ingress
      shell: "kubectl -n {{ item.value.namespace }} annotate ingress {{ item.value.name }} \
                virtual-server.f5.com/ip={{ public_ip }} \
                virtual-server.f5.com/partition={{ bigip_partition }}"
      with_dict: "{{ http_ingress }}"

    - name: attach a virtual server to kubernetes https ingress step first
      shell: "kubectl -n {{ item.value.namespace }} patch ingress {{ item.value.name }} \
                -p '{\"spec\":{\"tls\":[{\"secretName\":\"/Common/clientssl\"}]}}'"
      with_dict: "{{ https_ingress }}"

    - name: attach a virtual server to kubernetes https ingress step second
      shell: "kubectl -n {{ item.value.namespace }} annotate ingress {{ item.value.name }} \
                virtual-server.f5.com/ip={{ public_ip }} \
                virtual-server.f5.com/partition={{ bigip_partition }} \
                virtual-server.f5.com/serverssl=/Common/serverssl"
      with_dict: "{{ https_ingress }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true