- block:
    - name: 安装 rsync
      package: name=rsync state=present

    - name: 复制 manifests至 deploy节点
      synchronize: src=manifests dest={{ base_dir }}

  run_once: true
  when: "ansible_env['SSH_CLIENT'].split(' ')[0] != inventory_hostname"